[theme]
primaryColor = "#4B8BBE"  # 버튼 및 주요 강조 색
backgroundColor = "#FAFAFA"  # 전체 배경색
secondaryBackgroundColor = "#F0F4FF"  # 사이드바, 입력폼 배경색
textColor = "#262730"  # 전체 텍스트 색
font = "sans serif"  # 폰트 스타일
